# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server_interface.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(568, 586)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(161, 321, 256, 211))
        self.textBrowser.setObjectName("textBrowser")
        self.input_new_line = QtWidgets.QLineEdit(self.centralwidget)
        self.input_new_line.setGeometry(QtCore.QRect(116, 239, 341, 21))
        self.input_new_line.setObjectName("input_new_line")
        self.post = QtWidgets.QPushButton(self.centralwidget)
        self.post.setGeometry(QtCore.QRect(231, 270, 113, 32))
        self.post.setObjectName("post")
        self.home_icon = QtWidgets.QLabel(self.centralwidget)
        self.home_icon.setGeometry(QtCore.QRect(113, 45, 111, 71))
        self.home_icon.setStyleSheet("border-image: url(:/figure_lucy/America.png);")
        self.home_icon.setText("")
        self.home_icon.setObjectName("home_icon")
        self.vs_main = QtWidgets.QLabel(self.centralwidget)
        self.vs_main.setGeometry(QtCore.QRect(274, 64, 21, 31))
        self.vs_main.setStyleSheet("font: 20pt \"American Typewriter\";")
        self.vs_main.setObjectName("vs_main")
        self.guest_icon = QtWidgets.QLabel(self.centralwidget)
        self.guest_icon.setGeometry(QtCore.QRect(343, 45, 111, 71))
        self.guest_icon.setStyleSheet("border-image: url(:/figure_lucy/China.png);")
        self.guest_icon.setText("")
        self.guest_icon.setObjectName("guest_icon")
        self.Guest_label_main = QtWidgets.QLabel(self.centralwidget)
        self.Guest_label_main.setGeometry(QtCore.QRect(379, 130, 41, 16))
        self.Guest_label_main.setObjectName("Guest_label_main")
        self.Home_label_main = QtWidgets.QLabel(self.centralwidget)
        self.Home_label_main.setGeometry(QtCore.QRect(153, 130, 41, 16))
        self.Home_label_main.setObjectName("Home_label_main")
        self.guest_score = QtWidgets.QLabel(self.centralwidget)
        self.guest_score.setGeometry(QtCore.QRect(378, 170, 41, 21))
        self.guest_score.setStyleSheet("font: 18pt \"Arial Black\";")
        self.guest_score.setAlignment(QtCore.Qt.AlignCenter)
        self.guest_score.setObjectName("guest_score")
        self.home_score = QtWidgets.QLabel(self.centralwidget)
        self.home_score.setGeometry(QtCore.QRect(152, 170, 41, 21))
        self.home_score.setStyleSheet("font: 18pt \"Arial Black\";")
        self.home_score.setAlignment(QtCore.Qt.AlignCenter)
        self.home_score.setObjectName("home_score")
        self.colon = QtWidgets.QLabel(self.centralwidget)
        self.colon.setGeometry(QtCore.QRect(280, 170, 16, 21))
        self.colon.setStyleSheet("font: 18pt \"Arial Black\";")
        self.colon.setAlignment(QtCore.Qt.AlignCenter)
        self.colon.setObjectName("colon")
        self.home_three = QtWidgets.QPushButton(self.centralwidget)
        self.home_three.setGeometry(QtCore.QRect(30, 350, 113, 32))
        self.home_three.setObjectName("home_three")
        self.home_two = QtWidgets.QPushButton(self.centralwidget)
        self.home_two.setGeometry(QtCore.QRect(30, 400, 113, 32))
        self.home_two.setObjectName("home_two")
        self.home_one = QtWidgets.QPushButton(self.centralwidget)
        self.home_one.setGeometry(QtCore.QRect(30, 450, 113, 32))
        self.home_one.setObjectName("home_one")
        self.guest_three = QtWidgets.QPushButton(self.centralwidget)
        self.guest_three.setGeometry(QtCore.QRect(433, 350, 113, 32))
        self.guest_three.setObjectName("guest_three")
        self.guest_two = QtWidgets.QPushButton(self.centralwidget)
        self.guest_two.setGeometry(QtCore.QRect(433, 400, 113, 32))
        self.guest_two.setObjectName("guest_two")
        self.guest_one = QtWidgets.QPushButton(self.centralwidget)
        self.guest_one.setGeometry(QtCore.QRect(433, 450, 113, 32))
        self.guest_one.setObjectName("guest_one")
        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(250, 130, 71, 16))
        self.time.setStyleSheet("font: 18pt \"Arial Black\";")
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setObjectName("time")
        self.input_time = QtWidgets.QLineEdit(self.centralwidget)
        self.input_time.setGeometry(QtCore.QRect(230, 205, 113, 21))
        self.input_time.setAlignment(QtCore.Qt.AlignCenter)
        self.input_time.setObjectName("input_time")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Welcome to the broadcasting room.</p></body></html>"))
        self.post.setText(_translate("MainWindow", "post"))
        self.vs_main.setText(_translate("MainWindow", "vs"))
        self.Guest_label_main.setText(_translate("MainWindow", "Guest"))
        self.Home_label_main.setText(_translate("MainWindow", "Home"))
        self.guest_score.setText(_translate("MainWindow", "0"))
        self.home_score.setText(_translate("MainWindow", "0"))
        self.colon.setText(_translate("MainWindow", ":"))
        self.home_three.setText(_translate("MainWindow", "3-pt"))
        self.home_two.setText(_translate("MainWindow", "2-pt"))
        self.home_one.setText(_translate("MainWindow", "1-pt"))
        self.guest_three.setText(_translate("MainWindow", "3-pt"))
        self.guest_two.setText(_translate("MainWindow", "2-pt"))
        self.guest_one.setText(_translate("MainWindow", "1-pt"))
        self.time.setText(_translate("MainWindow", "12:00"))

import picture_lucy_rc
